name: test-model-install

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {os: windows-latest, r: 'release'}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: check

      - name: Clone allometric/allometric.
        run: |
          git clone https://github.com/allometric/allometric.git

      - name: Run install models test.
        run: |
          devtools::install("./allometric");
          devtools::load_all("./allometric");
          exit_data <- testthat::test_file("./allometric/tests/testthat/test-install.R");
          exit_data <- as.data.frame(exit_data);
          exit_code <- ifelse(sum(exit_data$failed, exit_data$error) == 0, 0, 1);
          quit(save = "no", status = exit_code, runLast = FALSE);
        shell: Rscript {0}

