name: test-model-install

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {os: windows-latest, r: 'release'}

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        Rscript -e 'install.packages("remotes")'
        Rscript -e 'remotes::install_github("allometric/allometric@model_migration")'
    - name: Run tests
      run: |
        Rscript -e 'library(allometric); testthat::test_file("tests/testthat/test-install.R")'
